name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test Makefile rules
        run: |
          make
          make clean
          make fclean
          make re
      - name: test executable exists with the good name
        run: |
          find "pbrain-gomoku-ai"

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create exectuable on windows
        run: |
          mkdir -p build
          cd build && cmake .. && cmake --build .

  coverage:
    needs: [ "build_linux" ]
    runs-on: ubuntu-22.04
    steps:
      - name: Install criterion
        run: |
          sudo apt-get install gcovr
          sudo apt-get install meson
          git clone --recursive https://github.com/Snaipe/Criterion Criterion
          cd Criterion
          meson build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build tests
        run: make run_tests
      - name: Build report
        run: gcovr --xml report.xml --exclude tests
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
          fail_ci_if_error: false

  mirroring:
    needs: [ "build_linux" ]
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}